### ISSUE TITLE
repo path varies for different users when registering a new package

### ISSUE THREAD

**Issue by mmiller-max** [GunnarFarneback/LocalRegistry.jl#44]
When I register a package, the `Package.toml` entry in the private registry looks like this:

```toml
name = "PackageName"
uuid = "--"
repo = "ssh://git@url.git"
subdir = "libs/PackageName"
```

When a different user does it, it looks likes this

```toml
name = "PackageName"
uuid = "--"
repo = "ssh://url.git"
subdir = "libs/PackageName"
```

The missing `git@` in the repo url causes the following error when trying to add the package

```
Cloning [--] PackageName from ssh://../.git
ERROR: LoadError: failed to clone from ssh://../.git, error: GitError(Code:EAUTH, Class:None, No errors)
```

Which can be worked around by 

```Julia
Pkg.GitTools.setprotocol!(domain="registry/domain", protocol="ssh",user="user")
```

The question is why is there a different in the repo path? Is this a bug or is it something in git credentials/how the original repository was cloned? Cheers.
